Feature/target tracking, landmark msg & action
vortexntnu/vortex-msgs pull request #6
Opened 2024-03-13 19:13 UTC by jorgenfj

Landmark msg and action for use in the landmark server
Also includes some msgs for the target tracking visualization. I am unsure of whether they are used or should be deleted.
Closes #3 
Closes #2

2024-03-21 12:47 UTC, alekskl01 requested changes

2024-03-21 12:47 UTC, alekskl01 commented on CMakeLists.txt
> +
Remove if not used

2024-03-21 12:47 UTC, alekskl01 commented on CMakeLists.txt
> +  "msg/ParameterArray.msg"
Remember to remove the unused messages here aswell.

2024-03-21 12:47 UTC, alekskl01 commented on msg/Parameter.msg
> +string type
What is the purpose of this message? Do we need a message for ROS parameters?

2024-03-21 16:22 UTC, TristanWolfram commented
I removed the messages in CMakeLists.txt as well. Also removed the comment since it is not used.
I don't know anything about the Parameter message. So, @jorgenfj du you know, if we need this?

2024-03-21 17:27 UTC, alekskl01 approved these changes

2024-03-21 17:31 UTC, merged

2024-03-22 08:02 UTC, jorgenfj commented on msg/Parameter.msg
> +string type
It is not necessary. Can be solved through param event callbacks. Will discuss with @etfroeland when he comes back. But should be kept for now to visualize results from easter testing