Service for local path planner
vortexntnu/vortex-msgs pull request #7
Opened 2024-03-17 16:06 UTC by Andeshog

Added a service for the local path planner.

`#request
float32[] waypoint
---
#response
bool success`

2024-03-17 16:45 UTC, alekskl01 commented on srv/MissionPlanner.srv
> +int32 gy
It is not really clear what these represent. Try to find some more descriptive variable names.

2024-03-17 16:45 UTC, alekskl01 commented on srv/MissionPlanner.srv
The service should probably be renamed to something that better represent its contents.

2024-03-17 17:11 UTC, alekskl01 commented on srv/MissionPlanner.srv
> +int32 gy
also, consider creating a 2D-point message with x and y instead of separating them into different variables for x and y

2024-03-18 15:36 UTC, alekskl01 commented on srv/MissionParameters.srv
> +int32[] obstacles_y
This could also use the Point2D message

2024-03-19 13:41 UTC, alekskl01 requested changes

2024-03-19 13:41 UTC, alekskl01 commented on srv/MissionParameters.srv
> +nav_2d_msgs/Point2D[] obstacles_y
Isnt one Point2D array enough?

2024-03-19 14:02 UTC, alekskl01 reviewed
What was the reason for switching to Point from Point2D?

2024-03-19 14:27 UTC, Andeshog commented
Because I could not find the Point2D msg anywhere in the documentation. I was also not able to colcon build. If it turns out there is no Point2D msg, would it be easier to make our own? Such that we dont have to deal with the z value of the point. https://index.ros.org/p/nav_2d_msgs/github-ros-planning-navigation2/#humble-assets

2024-03-19 14:28 UTC, alekskl01 commented
Ah ok, regular points works fine for now.

2024-03-19 14:30 UTC, alekskl01 approved these changes

2024-03-19 14:30 UTC, merged